import type { Metadata } from "next";
import "./globals.css";
import { PrimeReactProvider } from 'primereact/api';
import NavMenu from "@/components/header/NavMenu";
import {auth} from "@/auth";
import SessionProvider from "@/providers/SessionProvider";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`antialiased flex flex-col min-h-screen p-2`} >
            <SessionProvider>
                <PrimeReactProvider>
                    <NavMenu/>
                    <div className="h-full container mx-auto flex-grow">
                        {children}
                    </div>
                </PrimeReactProvider>
            </SessionProvider>
            <Footer/>
        </body>
        </html>
    );
}
